version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  python-executor:
    working_directory: ~/memoria
    docker:
      - image: circleci/python:3.8

commands:
  install-packages:
    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}

      - run:
          name: Create Virtual Environment and Install Dependencies
          command: |
            virtualenv env
            source env/bin/activate
            pip install -r requirements.txt -r requirements-dev.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "env"

jobs:
  run-test:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run Tests and Coverage
          command: |
            source env/bin/activate
            pytest --cov .

      - run: ls .coverage

      - codecov/upload

  check-linting:
    executor: python-executor
    steps:
      - install-packages

      - run:
          name: Run black, isort
          command: |
            source env/bin/activate
            black --check memoria tests
            isort memoria tests

workflows:
  main:
    jobs:
      - run-test
      - check-linting
